---
site_name: "@.link"
docs_dir: content
theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.expand

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences